// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfqhntdyrtzvbkiekult.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmcWhudGR5cnR6dmJraWVrdWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzU1NDMsImV4cCI6MjA2OTIxMTU0M30.E1mnbtzJduJGi2uui3-EowFNk3WfBr60r_kFpLOdjUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});